# Generated by Django 3.0.6 on 2020-05-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='carco',
            new_name='cargo',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='modificacao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='modificacao',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='modificacao',
        ),
        migrations.AddField(
            model_name='cargo',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='modificado'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='modificado'),
        ),
        migrations.AddField(
            model_name='servico',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='modificado'),
        ),
    ]
