# Generated by Django 3.0.6 on 2020-05-10 16:04

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200510_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_name, verbose_name='Imagem'),
        ),
    ]
